### PR TITLE
use Cache::FastMmap instead of IPC::ShareLite

### PR DESCRIPTION
**Pull request by elcamlost**

### CODE REVIEW

**Comment by kraih** [comment]
No description? What are we supposed to do with this?

**Comment by kraih** [comment]
How does `Cache::FastMmap` compare to `IPC::ShareLite`? What are the performance characteristics? How well does it scale?

**Comment by elcamlost** [comment]
I didn't make benchmarks by myself, but [Cache::FastMmap docs](https://metacpan.org/pod/Cache::FastMmap#PERFORMANCE) states that this module much faster than IPC::ShareLite in cases of multiple keys to store.

We are using Cache::FastMmap in production to share inner process cache between workers and it works fast and stable in a fairly loaded environment (more than hundred rps per worker).

**Comment by kraih** [comment]
This solution is not actually feasible, because `Cache::FastMmap` limits any individual value to the system page size.

**Comment by kraih** [comment]
We now use `File::Map` instead.

**Pull request closed without merging**
